# Railway.app Deployment Configuration
# This file tells Railway how to build and deploy your ASP.NET Core app.

[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet IncomeExpenseApp.dll"

# Volume for persistent SQLite database
[[deploy.volumes]]
mountPath = "/data"